#!/usr/bin/env bash
set -e

# Current branch name
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

# Regex rules
BRANCH_REGEX='^[A-Z0-9]+-[0-9]+-[a-z0-9._-]+$'

# echo "🔎 Checking branch name..."
if [[ "$BRANCH_NAME" == "master" || "$BRANCH_NAME" == "main" ]]; then
  :
elif ! [[ "$BRANCH_NAME" =~ $BRANCH_REGEX ]]; then
  echo "❌ Invalid branch name: $BRANCH_NAME"
  echo "👉 Must match: ABC-123-some-description (prefix can be uppercase alphanumeric), or be 'master'/'main'"
  exit 1
fi
# echo "✅ Branch name OK: $BRANCH_NAME"
